defaults:
  - default.yaml

lr: 0.001  # from PN2 paper - quite sensitive!

neural_net_class_name: "PointNet2"
neural_net_hparams:
  d_in: ${model.d_in}  # 3 (xyz) + num of features
  num_classes: "${model.num_classes}"
  r1: 2
  r2: 4
