ToTensor:
  _target_: myria3d.data.transforms.ToTensor

CopyFullPos:
  _target_: myria3d.data.transforms.CopyFullPos

GridSampling:
  _target_: torch_geometric.transforms.GridSampling
  _args_:
    - 0.25

FixedPoints:
  _target_: torch_geometric.transforms.FixedPoints
  _args_:
    - 20000
  replace: False
  allow_duplicates: True

CopySampledPos:
  _target_: myria3d.data.transforms.CopySampledPos

Center:
  _target_: torch_geometric.transforms.Center