ToTensor:
  _target_: myria3d.data.transforms.ToTensor

TargetTransform:
  _target_: myria3d.data.transforms.TargetTransform
  _args_:
    - ${datamodule.dataset_description.classification_preprocessing_dict}
    - ${datamodule.dataset_description.classification_dict}

GridSampling:
  _target_: torch_geometric.transforms.GridSampling
  _args_:
    - 0.25

FixedPoints:
  _target_: torch_geometric.transforms.FixedPoints
  _args_:
    - 20000
  replace: False
  allow_duplicates: True

Center:
  _target_: torch_geometric.transforms.Center