_target_: myria3d.data.datamodule.DataModule

# Directory with test, train, val prepared subdirs
prepared_data_dir: ${oc.env:PREPARED_DATA_DIR}
# Possibility to override test annotated LAS data directly with any folder
test_data_dir: ${datamodule.prepared_data_dir}/test/

batch_size: 32
prefetch_factor: 2
num_workers: 2  # for data loaders
subtile_width_meters: 50  # size of receptive fields : 50mx50m
subtile_overlap: ${predict.subtile_overlap}  # Used for test and predict phases only

defaults:
  - dataset_description: 20220204_BuildingValidation_and_Ground.yaml
  - transforms: default.yaml
