# Positions need to be normalized between [-1;1] for current RandLaNet

NullifyLowestZ:
  _target_: myria3d.data.transforms.NullifyLowestZ

NormalizePos:
  _target_: myria3d.data.transforms.NormalizePos
  subtile_width_meters: ${datamodule.subtile_width_meters}

StandardizeFeatures:
  _target_: myria3d.data.transforms.StandardizeFeatures