defaults:
  - preparations: train.yaml
  - augmentations: default.yaml
  - normalizations: randla_net_scheme_normalized_pos.yaml

# trun these dict into ListConfig
augmentations_list: "${oc.dict.values: datamodule.transforms.augmentations}"
preparations_list: "${oc.dict.values: datamodule.transforms.preparations}"
normalizations_list: "${oc.dict.values: datamodule.transforms.normalizations}"
