name: CICD

on:
  # Run CICD for non-draft pull request
  pull_request:
    branches:
      - dev
      - main
  # Also run when the pull request merges (which generates a push)
  # So that we can tag the docker image appropriately.
  push:
    branches:
      - cicd  # temporary, for development only
      - dev
      - prod
      - main

jobs:
  CICD:
    runs-on: self-hosted

    steps:

    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker build -t lidar_deep_im .

    - name: Check code neatness (linter)
      run: docker run lidar_deep_im flake8

    - name: unit testing
      run: docker run lidar_deep_im pytest --ignore=actions-runner --ignore="notebooks"

    - name: Full module run on LAS subset
      run: docker run -v /var/data/CICD_github_assets:/CICD_github_assets lidar_deep_im 

    - name: save the docker image because everything worked
      run: docker save lidar_deep_im:latest > /var/data/CICD_github_assets/lidar_deep_im.tar # need writing right

    - name: clean the server for further uses
      if: always()  # always do it, even if something failed
      run: docker system prune  # remove obsolete docker images (take a HUGE amount of space)


      
